
import { Department, Category, Product, Brand, Banner, User, UserRole, StoreSettings } from './types';

export const INITIAL_USER: User = {
  id: 'user-admin',
  name: 'Administrador Supritec',
  email: 'admin@supritec.com.br',
  role: UserRole.ADMIN,
  createdAt: new Date().toISOString()
};

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  name: 'Supritec Informática',
  logoUrl: 'logo.png',
  email: 'sac@supritec.com.br',
  phone: '(11) 4004-9000',
  whatsapp: '(11) 99999-9999',
  address: {
    street: 'Av. Tecnológica',
    number: '1000',
    neighborhood: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    zip: '01000-000'
  },
  openingHours: 'Segunda à Sexta, das 9h às 18h',
  socials: {
    facebook: '#',
    instagram: '#',
    twitter: '#',
    youtube: '#'
  }
};

export const DEPARTMENTS: Department[] = [
  { id: 'dep-1', name: 'Computadores', slug: 'computadores', order: 1, active: true },
  { id: 'dep-2', name: 'Celulares', slug: 'celulares', order: 2, active: true },
  { id: 'dep-3', name: 'Games', slug: 'games', order: 3, active: true },
  { id: 'dep-4', name: 'Áudio & Vídeo', slug: 'audio-video', order: 4, active: true },
  { id: 'dep-5', name: 'Redes', slug: 'redes', order: 5, active: true },
];

export const CATEGORIES: Category[] = [
  { id: 'cat-1', departmentId: 'dep-1', name: 'Notebooks', slug: 'notebooks', order: 1, active: true },
  { id: 'cat-2', departmentId: 'dep-1', name: 'Desktops', slug: 'desktops', order: 2, active: true },
  { id: 'cat-3', departmentId: 'dep-1', name: 'Acessórios', slug: 'acessorios', order: 3, active: true },
  { id: 'cat-4', departmentId: 'dep-2', name: 'Smartphones', slug: 'smartphones', order: 1, active: true },
  { id: 'cat-5', departmentId: 'dep-3', name: 'Consoles', slug: 'consoles', order: 1, active: true },
  { id: 'cat-6', departmentId: 'dep-4', name: 'Fones', slug: 'fones', order: 1, active: true },
];

export const BRANDS: Brand[] = [
  { id: 'brand-1', name: 'Apple', slug: 'apple' },
  { id: 'brand-2', name: 'Samsung', slug: 'samsung' },
  { id: 'brand-3', name: 'Dell', slug: 'dell' },
  { id: 'brand-4', name: 'Sony', slug: 'sony' },
  { id: 'brand-5', name: 'Logitech', slug: 'logitech' },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    categoryId: 'cat-1',
    brandId: 'brand-3',
    name: 'Notebook Dell Inspiron 15',
    slug: 'notebook-dell-inspiron-15',
    description: 'Alta performance para o dia a dia.',
    specs: 'Processador Intel i7, 16GB RAM, 512GB SSD',
    price: 4999.00,
    salePrice: 4499.00,
    sku: 'DELL-INS-15-7',
    stock: 10,
    weight: 1.8,
    width: 35,
    height: 2,
    length: 25,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/laptop1/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-2',
    categoryId: 'cat-4',
    brandId: 'brand-1',
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max-256gb',
    description: 'O melhor iPhone de todos os tempos.',
    specs: 'Chip A17 Pro, Câmera 48MP, Tela 6.7"',
    price: 9999.00,
    salePrice: 8999.00,
    sku: 'AAPL-IPH-15-PM',
    stock: 5,
    weight: 0.22,
    width: 8,
    height: 16,
    length: 1,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/iphone15/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-3',
    categoryId: 'cat-5',
    brandId: 'brand-4',
    name: 'PlayStation 5 com 1 Controle',
    slug: 'playstation-5-console',
    description: 'Jogue como nunca antes.',
    specs: 'SSD Ultra rápido, Ray Tracing, 4K HDR',
    price: 4499.00,
    salePrice: 3999.00,
    sku: 'SONY-PS5-001',
    stock: 15,
    weight: 4.5,
    width: 39,
    height: 10,
    length: 26,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/ps5/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-4',
    categoryId: 'cat-6',
    brandId: 'brand-5',
    name: 'Mouse Gamer Logitech G502',
    slug: 'mouse-logitech-g502',
    description: 'Precisão extrema para gamers.',
    specs: 'Sensor HERO 25K, 11 botões programáveis',
    price: 499.00,
    salePrice: 399.00,
    sku: 'LOGI-G502',
    stock: 50,
    weight: 0.12,
    width: 7,
    height: 4,
    length: 13,
    featured: false,
    active: true,
    images: ['https://picsum.photos/seed/mouse1/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-5',
    categoryId: 'cat-6',
    brandId: 'brand-2',
    name: 'Samsung Galaxy Buds 2 Pro',
    slug: 'galaxy-buds-2-pro',
    description: 'Som imersivo de alta qualidade.',
    specs: 'Cancelamento ativo de ruído, Áudio 360',
    price: 1299.00,
    salePrice: 899.00,
    sku: 'SAMS-BUDS-2P',
    stock: 30,
    weight: 0.05,
    width: 5,
    height: 3,
    length: 5,
    featured: false,
    active: true,
    images: ['https://picsum.photos/seed/buds/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-6',
    categoryId: 'cat-1',
    brandId: 'brand-1',
    name: 'MacBook Air M2 8GB/256GB',
    slug: 'macbook-air-m2',
    description: 'Fino, leve e potente.',
    specs: 'Chip M2, Tela Liquid Retina 13.6"',
    price: 11599.00,
    salePrice: 9499.00,
    sku: 'AAPL-MBA-M2',
    stock: 8,
    weight: 1.24,
    width: 30,
    height: 1,
    length: 21,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/macbook/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-7',
    categoryId: 'cat-4',
    brandId: 'brand-2',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'galaxy-s24-ultra',
    description: 'IA generativa na palma da mão.',
    specs: 'Snapdragon 8 Gen 3, Câmera 200MP',
    price: 8999.00,
    salePrice: 7499.00,
    sku: 'SAMS-S24-U',
    stock: 12,
    weight: 0.23,
    width: 8,
    height: 16,
    length: 1,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/s24u/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-8',
    categoryId: 'cat-5',
    brandId: 'brand-4',
    name: 'Controle DualSense PS5',
    slug: 'dualsense-ps5-white',
    description: 'Resposta tátil e gatilhos adaptáveis.',
    specs: 'Wireless, Bateria recarregável',
    price: 499.00,
    salePrice: 429.00,
    sku: 'SONY-DS5-W',
    stock: 40,
    weight: 0.3,
    width: 16,
    height: 10,
    length: 6,
    featured: false,
    active: true,
    images: ['https://picsum.photos/seed/dualsense/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-9',
    categoryId: 'cat-6',
    brandId: 'brand-4',
    name: 'Headset Sony WH-1000XM5',
    slug: 'sony-wh1000xm5',
    description: 'Líder em cancelamento de ruído.',
    specs: 'Bateria de 30h, Som Hi-Res',
    price: 2999.00,
    salePrice: 2499.00,
    sku: 'SONY-WH5-B',
    stock: 15,
    weight: 0.25,
    width: 18,
    height: 22,
    length: 8,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/sonyhead/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-10',
    categoryId: 'cat-3',
    brandId: 'brand-5',
    name: 'Teclado Mecânico Logitech G915',
    slug: 'logitech-g915-tkl',
    description: 'Performance sem fio compacta.',
    specs: 'Switches GL de baixo perfil, RGB Lightsync',
    price: 1599.00,
    salePrice: 1299.00,
    sku: 'LOGI-G915-TKL',
    stock: 20,
    weight: 0.8,
    width: 36,
    height: 2,
    length: 15,
    featured: false,
    active: true,
    images: ['https://picsum.photos/seed/keyboard/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-11',
    categoryId: 'cat-2',
    brandId: 'brand-3',
    name: 'PC Gamer Dell G15 Desktop',
    slug: 'dell-g15-desktop',
    description: 'Pronto para os jogos mais pesados.',
    specs: 'RTX 4060, Intel i5 13a Gen, 1TB NVMe',
    price: 6999.00,
    salePrice: 6299.00,
    sku: 'DELL-G15-DT',
    stock: 5,
    weight: 7.5,
    width: 17,
    height: 37,
    length: 31,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/desktop1/600/600'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-12',
    categoryId: 'cat-4',
    brandId: 'brand-1',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-s9',
    description: 'Mais inteligente, mais brilhante.',
    specs: 'S9 SiP, Gesto de toque duplo, Oxigênio no sangue',
    price: 4999.00,
    salePrice: 3899.00,
    sku: 'AAPL-AW-S9',
    stock: 18,
    weight: 0.04,
    width: 4,
    height: 4,
    length: 1,
    featured: true,
    active: true,
    images: ['https://picsum.photos/seed/watch/600/600'],
    createdAt: new Date().toISOString()
  },
];

export const SEED_BANNERS: Banner[] = [
  {
    id: 'ban-1',
    position: 'hero',
    title: 'O Futuro é Agora na Supritec',
    subtitle: 'Confira as melhores ofertas em tecnologia gamer e profissional.',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2072',
    linkUrl: '/catalogo',
    order: 1,
    active: true
  },
  {
    id: 'ban-2',
    position: 'secondary_1',
    title: 'Smartphones de Última Geração',
    subtitle: 'Até 20% OFF em iPhones e Galaxy S24.',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=1780',
    linkUrl: '/catalogo/celulares',
    order: 1,
    active: true
  },
  {
    id: 'ban-3',
    position: 'secondary_2',
    title: 'Setup Gamer dos Sonhos',
    subtitle: 'Teclados, mouses e headsets com preço imbatível.',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=2070',
    linkUrl: '/catalogo/games',
    order: 1,
    active: true
  }
];
